In [38]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
dataset = pd.get_dummies(dataset,drop_first=True)
# dataset.columns
independ= dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
                   'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
                   'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
depend = dataset[['classification_yes']]

#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independ, depend, test_size = 1/3, random_state = 0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV

# class sklearn.naive_bayes.MultinomialNB(*, alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None)[source]

# param_grid = {'alpha':[1.0,2.0],
#              'force_alpha':[True,False],
#              'fit_prior':[True,False],
#              'class_prior':[None]}

param_grid={}

grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

# fitting the model for grid search 
grid.fit(X_train, y_train) 

grid_predictions = grid.predict(X_test) # Pass test set for prediction

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


# classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
# {'weighted', 'samples', 'binary', 'micro', 'macro'} 
f1_micro=f1_score(y_test,grid_predictions,average='weighted')

from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

print("\nMultinomial Naive Bbayes Grid Classifiction Report:\n")
print("The confusion_matrix value:\n\n {}".format(cm))
print("The classification_report value:\n\n {}".format(clf_report))
print("The f1_micro value : {}\n".format(f1_micro))
print("The roc_auc_score value for best parameter {}: {}\n".format(grid.best_params_, roc))

# df = pd.DataFrame(cv_result)
# df
# Convert DataFrame to markdown table
# table = df.to_markdown(index=False)
# print(table)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

Multinomial Naive Bbayes Grid Classifiction Report:

The confusion_matrix value:

 [[50  1]
 [23 59]]
The classification_report value:

               precision    recall  f1-score   support

       False       0.68      0.98      0.81        51
        True       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

The f1_micro value : 0.8215780250262184

The roc_auc_score value for best parameter {}: 1.0



C:\Users\ranja\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
dataset = pd.get_dummies(dataset,drop_first=True)
# dataset.columns
independ= dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
                   'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
                   'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
depend = dataset[['classification_yes']]

#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independ, depend, test_size = 1/3, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV

# class sklearn.naive_bayes.MultinomialNB(*, alpha=1.0, force_alpha=True, fit_prior=True, class_prior=None)[source]

param_grid={}

grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

# fitting the model for grid search 
grid.fit(X_train, y_train) 

grid_predictions = grid.predict(X_test) # Pass test set for prediction

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


# classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
# {'weighted', 'samples', 'binary', 'micro', 'macro'} 
f1_micro=f1_score(y_test,grid_predictions,average='weighted')

from sklearn.metrics import roc_auc_score
roc = roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

cv_result=grid.cv_results_

print("\nBernoulli Naive Bbayes Grid Classifiction Report:\n")
print("The confusion_matrix value:\n\n {}".format(cm))
print("The classification_report value:\n\n {}".format(clf_report))
print("The f1_micro value : {}\n".format(f1_micro))
print("The roc_auc_score value : {}\n".format( roc))

# df = pd.DataFrame(cv_result)
# df
# Convert DataFrame to markdown table
# table = df.to_markdown(index=False)
# print(table)

Fitting 5 folds for each of 1 candidates, totalling 5 fits

Bernoulli Naive Bbayes Grid Classifiction Report:

The confusion_matrix value:

 [[51  0]
 [ 3 79]]
The classification_report value:

               precision    recall  f1-score   support

       False       0.94      1.00      0.97        51
        True       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

The f1_micro value : 0.9775556904684072

The roc_auc_score value : 1.0



C:\Users\ranja\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [76]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
dataset = pd.get_dummies(dataset,drop_first=True)
# dataset.columns
independ= dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
                   'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
                   'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
depend = dataset[['classification_yes']]

#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independ, depend, test_size = 1/3, random_state = 0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

from sklearn.naive_bayes import CategoricalNB
# from sklearn.model_selection import GridSearchCV
param_grid={}

# grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid = CategoricalNB()
# fitting the model for grid search 
grid.fit(independ, depend) 

grid_predictions = grid.predict(X_test) # Pass test set for prediction

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


# classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
# {'weighted', 'samples', 'binary', 'micro', 'macro'} 
f1_micro=f1_score(y_test,grid_predictions,average='micro')

# from sklearn.metrics import roc_auc_score
# roc = roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

# cv_result=grid.cv_results_

print("\nCategorical Naive Bbayes Grid Classifiction Report:\n")
print("The confusion_matrix value:\n\n {}".format(cm))
print("The classification_report value:\n\n {}".format(clf_report))
print("The f1_micro value : {}\n".format(f1_micro))
# print("The roc_auc_score value : {}\n".format( roc))

# df = pd.DataFrame(cv_result)
# df
# Convert DataFrame to markdown table
# table = df.to_markdown(index=False)
# print(table)


Categorical Naive Bbayes Grid Classifiction Report:

The confusion_matrix value:

 [[51  0]
 [ 1 81]]
The classification_report value:

               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

The f1_micro value : 0.9924812030075187



C:\Users\ranja\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [78]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
dataset = pd.get_dummies(dataset,drop_first=True)
# dataset.columns
independ= dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
                   'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
                   'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
depend = dataset[['classification_yes']]

#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independ, depend, test_size = 1/3, random_state = 0)

from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
param_grid={}

grid = GridSearchCV(CategoricalNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 

# fitting the model for grid search 
grid.fit(independ, depend) 

grid_predictions = grid.predict(X_test) # Pass test set for prediction

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)


# classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

from sklearn.metrics import f1_score
# {'weighted', 'samples', 'binary', 'micro', 'macro'} 
f1_micro=f1_score(y_test,grid_predictions,average='micro')

from sklearn.metrics import roc_auc_score
roc = roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

cv_result=grid.cv_results_

print("\nComplement Naive Bbayes Grid Classifiction Report:\n")
print("The confusion_matrix value:\n\n {}".format(cm))
print("The classification_report value:\n\n {}".format(clf_report))
print("The f1_micro value : {}\n".format(f1_micro))
print("The roc_auc_score value : {}\n".format( roc))

# df = pd.DataFrame(cv_result)
# df
# Convert DataFrame to markdown table
# table = df.to_markdown(index=False)
# print(table)


Fitting 5 folds for each of 1 candidates, totalling 5 fits

Complement Naive Bbayes Grid Classifiction Report:

The confusion_matrix value:

 [[51  0]
 [ 1 81]]
The classification_report value:

               precision    recall  f1-score   support

       False       0.98      1.00      0.99        51
        True       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

The f1_micro value : 0.9924812030075187

The roc_auc_score value : 1.0



C:\Users\ranja\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [nan]
  warnings.warn(
C:\Users\ranja\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
